# Generated by Django 5.0.6 on 2025-01-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("url", models.URLField()),
                ("qr_code", models.ImageField(blank=True, upload_to="qrcodes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
